# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-05 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20200304_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocarrito',
            name='status',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='crud.StatusCarrito'),
        ),
    ]
